Repository FWDekker/fo76-dumps, pull requests merged in 2020-09, with the labels that each got.

#24 Add support for big terminal entries
  Edit scripts/ExportLargeFile.pas
  Edit scripts/ExportTabularIDs.pas
  Edit scripts/ExportWikiTERM.pas
Labels: bug

#25 Write "done" file after completing dumps
  Edit scripts/ExportAll.fo76pas
Labels: feature

#26 Remove italics around empty script notes
  Edit scripts/ExportCore.pas
  Edit scripts/ExportWikiDIAL.pas
Labels: bug

#20 Added Flora, Leveled Items, Weapons, Item locations
  Edit scripts/ExportAll.pas
  Edit scripts/ExportCore.pas
  Edit scripts/ExportJson.pas
  Edit scripts/ExportTabularARMO.pas
  Edit scripts/ExportTabularCLAS.pas
  Edit scripts/ExportTabularCore.pas
  Edit scripts/ExportTabularFACT.pas
  Edit scripts/ExportTabularFLOR.pas
  Edit scripts/ExportTabularLOC.pas
  Edit scripts/ExportTabularLVLI.pas
  Edit scripts/ExportTabularMISC.pas
  Edit scripts/ExportTabularNPC_.pas
  Edit scripts/ExportTabularRACE.pas
  Edit scripts/ExportTabularWEAP.pas
  README.md
Labels: dump-request
